export const metadata = {
  title: "Mis Datos",
  description: "Generated by create next app",
};

export default function clientesLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <section>{children}</section>;
}
