export const metadata = {
  title: "Inscribirse a una Clase",
  description: "Generated by create next app",
};

export default function inscribirseLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <section>{children}</section>;
}
