export const metadata = {
  title: "Reporte de ventas",
  description: "Generated by create next app",
};

export default function reportesLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <section>{children}</section>;
}
