export const metadata = {
  title: "Reporte de ventas",
  description: "Generated by create next app",
};

export default function reportesLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <section className="bg-white">{children}</section>;
}
