export const metadata = {
  title: "Ventas",
  description: "Generated by create next app",
};

export default function ventasLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <section>{children}</section>;
}
