import "./globals.css";

import { Database } from "../types/supabase";
import type { SupabaseClient } from "@supabase/auth-helpers-nextjs";
import SupabaseListener from "../components/supabase-listener";
import { createServerClient } from "../utils/supabase-server";
import SupabaseProvider from "../components/supabase-provider";

import NavigationMenu from "../react_components/navBar";

import "tailwindcss/tailwind.css";
import { AboutUs } from "./about";

// do not cache this layout
export const revalidate = 0;

export type TypedSupabaseClient = SupabaseClient<Database>;

export const metadata = {
  title: "Pagina de Inicio",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const supabase = createServerClient();

  const {
    data: { session },
  } = await supabase.auth.getSession();
  return (
    <html lang="en">
      <body>
        <SupabaseProvider session={session}>
          <SupabaseListener serverAccessToken={session?.access_token} />

          <NavigationMenu>
            {" "}
            {children}
            <AboutUs />
          </NavigationMenu>
        </SupabaseProvider>
      </body>
    </html>
  );
}
