export const metadata = {
  title: "Alumnos de las Clases",
  description: "Generated by create next app",
};

export default function misAlumnosLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <section>{children}</section>;
}
