export const metadata = {
  title: "Comprobacion de Ingresos",
  description: "Generated by create next app",
};

export default function ingresoLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <section>{children}</section>;
}
