export const metadata = {
  title: "Inventarios",
  description: "Generated by create next app",
};

export default function inventarioLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <section>{children}</section>;
}
